In [1]:
import tensorflow as tf

Tensor flow works as a graph. The tensor operations are considered a node while a tensor is an edge in the graph.

In [2]:
g = tf.Graph() #Create a tensorflow graph

In [3]:
#Adding constants means adding operations that are
#going to produce the value of the constant
with g.as_default():
    a = tf.constant([2], name ='constant_a')
    b = tf.constant([3], name = 'constant_b')

In [4]:
a

<tf.Tensor 'constant_a:0' shape=(1,) dtype=int32>

In [5]:
sess = tf.compat.v1.Session(graph = g) #Create a session
result = sess.run(a) #Run the session on a constant
sess.close() #close a session
#To automatically close a session it can be used with the operaiton 'with'

In [6]:
print(result)

[2]


In [7]:
#Operation over tensors
with g.as_default():
    c = tf.add(a,b)
print(c)

Tensor("Add:0", shape=(1,), dtype=int32)


In [8]:
#To see the result we need to run a session
sess = tf.compat.v1.Session(graph = g)
result = sess.run(c)
sess.close()

In [9]:
print(result)

[5]


## Multi Dimensional Arrays

In [10]:
g2 = tf.Graph()
with g2.as_default():
    zeroD = tf.constant(1)
    oneD = tf.constant([3,5,8])
    twoD = tf.constant([[2,4,6],[0,8,5,],[6,3,2]])
    threeD = tf.constant([ [[1,2,3],[3,7,4],[2,35,5]] , [[4,5,6],[5,6,7],[6,7,8]] , [[7,8,9],[8,9,10],[9,10,11]] ])
    addition = tf.add(zeroD,zeroD)
    multiplication = tf.matmul(threeD,threeD)
    
with tf.compat.v1.Session(graph = g2) as sess:
    result = sess.run(zeroD)
    print("0 Dimensional:\n %s\n"%result)
    print("0 Dimensional shape:\n %s\n"%zeroD.shape)
    result = sess.run(oneD)
    print("1 Dimensional:\n %s\n"%result)
    print("1 Dimensional shape:\n %s\n"%oneD.shape)
    result = sess.run(twoD)
    print("2 Dimensional:\n %s\n"%result)
    print("2 Dimensional shape:\n %s\n"%twoD.shape)
    result = sess.run(threeD)
    print("3 Dimensional:\n %s\n"%result)
    print("3 Dimensional shape:\n %s\n"%threeD.shape)
    print("Addition Result:\n %s \n"%addition)
    print("Multiplication Reslut:\n %s \n"%multiplication)

0 Dimensional:
 1

0 Dimensional shape:
 ()

1 Dimensional:
 [3 5 8]

1 Dimensional shape:
 (3,)

2 Dimensional:
 [[2 4 6]
 [0 8 5]
 [6 3 2]]

2 Dimensional shape:
 (3, 3)

3 Dimensional:
 [[[ 1  2  3]
  [ 3  7  4]
  [ 2 35  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]]

3 Dimensional shape:
 (3, 3, 3)

Addition Result:
 Tensor("Add:0", shape=(), dtype=int32) 

Multiplication Reslut:
 Tensor("MatMul:0", shape=(3, 3, 3), dtype=int32) 



## Variables in Tensorflow

In [11]:
var = tf.Variable(1) #Defining a variable

In [12]:
update = tf.compat.v1.assign(var, var *2) 
#Defining the update rate

In [13]:
init_op = tf.compat.v1.global_variables_initializer()
#Variable initializer

In [14]:
with tf.compat.v1.Session() as session:
    var = tf.Variable(1)
    update = tf.compat.v1.assign(var, var *2)
    init_op = tf.compat.v1.global_variables_initializer()
    session.run(init_op)
    print(session.run(var))
    for _ in range(3):
        session.run(update)
        print(session.run(var))

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
1
2
4
8


## Placeholders

Placeholders are input ways in which your model accepts inputs.

In [15]:
tf.compat.v1.disable_eager_execution() #This is because I am on the latest vesion
a = tf.compat.v1.placeholder(tf.float32) #Define a placeholder

In [16]:
b = a * 5 #Define the operation 

In [17]:
with tf.compat.v1.Session() as sees:
    result = sees.run(b,feed_dict = {a:5.0})
    print(result)

25.0


In [18]:
with tf.compat.v1.Session() as sees:
    #We can pass anything as an input
    result = sees.run(b,feed_dict = {a:[5.0,10,99]})
    print(result)

[ 25.  50. 495.]
